package Main;

//PUBLIC CLASS GRAVITYCALCULATOR {
//
//	PUBLIC STATIC VOID MAIN(STRING[] ARGS) {
//		// TODO AUTO-GENERATED METHOD STUB
//		DOUBLE GRAVITY = -9.81;// EARTH'S GRAVITY IN M/S^2
//		DOUBLE INITIALVELOCITY = 0;
//		DOUBLE FALLINGTIME = 10.0;
//		DOUBLE INITIALPOSITION = 0;
//		DOUBLE FINALPOSITION = 0;
//		
//		FINALPOSITION = .5*GRAVITY*FALLINGTIME*FALLINGTIME + INITIALVELOCITY*FALLINGTIME + INITIALPOSITION;
//		
//		SYSTEM.OUT.PRINTLN("THE OBJECTS POSITION AFTER " + FALLINGTIME + " SECONDS IS " + FINALPOSITION + "M");
//		
//	}
//
//}
